SELECT
    IM1.PORT_CODE AS 港コード,
    PT.PORT_NAME AS 港名,
    IM1.AMT AS 入国者数,
    IM2.AMT AS 出国者数,
    (IM1.AMT - IM2.AMT) AS 差分
FROM
    IMMIGRATION IM1
    INNER JOIN IMMIGRATION IM2 ON IM1.PORT_CODE = IM2.PORT_CODE
    AND IM1.GROUP_CODE = IM2.GROUP_CODE
    INNER JOIN PORT PT ON PT.PORT_CODE = IM1.PORT_CODE
WHERE
    IM1.GROUP_CODE = '120'
    AND IM1.KIND_CODE = '110'
    AND IM2.KIND_CODE = '120'
    AND IM1.AMT - IM2.AMT > 0
ORDER BY
    差分 DESC,
    IM1.PORT_CODE DESC;